import { PrismaClient } from "@prisma/client";

/**
 * Single database entry point for the whole app.
 *
 * The active engine is chosen from the DATABASE_URL protocol at runtime:
 *   - postgres:// / postgresql:// → PostgreSQL client (Vercel + Supabase in production)
 *   - anything else (file: SQLite)   → SQLite client (local development, zero setup)
 *
 * Both Prisma clients are generated by the `postinstall` script:
 *   - @prisma/client      from prisma/schema.prisma      (SQLite)
 *   - @prisma-pg/client   from prisma/schema.pg.prisma   (PostgreSQL)
 * The PostgreSQL client is required lazily so environments that never use it
 * (local dev) don't need it to exist.
 */

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

function createPrismaClient(): PrismaClient {
  const url = process.env.DATABASE_URL ?? "";

  if (url.startsWith("postgres://") || url.startsWith("postgresql://")) {
    // PostgreSQL — generated into node_modules/@prisma-pg/client (see postinstall).
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { PrismaClient: PrismaPg } = require("@prisma-pg/client") as typeof import("@prisma/client");
    return new PrismaPg() as unknown as PrismaClient;
  }

  // SQLite — local development.
  return new PrismaClient({
    log: ["query"],
  });
}

export const db = globalForPrisma.prisma ?? createPrismaClient();

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = db;
