import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  output: "standalone",
  // Keep Prisma out of the server bundle so its query engines load at runtime.
  // "@prisma-pg/client" is generated by postinstall (prisma/schema.pg.prisma).
  serverExternalPackages: ["@prisma/client", "@prisma-pg/client", "prisma"],
  typescript: {
    ignoreBuildErrors: true,
  },
  reactStrictMode: false,
};

export default nextConfig;
