import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // `standalone` output is ONLY for local/self-hosted preview (bun .next/standalone/server.js).
  // On Vercel it must be OFF — Vercel's own Next.js runtime builds its own output format,
  // and a forced standalone output can leave the deployment with nothing to serve.
  ...(process.env.VERCEL ? {} : { output: "standalone" as const }),
  // Keep Prisma out of the server bundle so its query engines load at runtime.
  // "@prisma-pg/client" is generated by postinstall (prisma/schema.pg.prisma).
  serverExternalPackages: ["@prisma/client", "@prisma-pg/client", "prisma"],
  typescript: {
    ignoreBuildErrors: true,
  },
  reactStrictMode: false,
};

export default nextConfig;
